import { Producto } from './models/producto';

export const ProductosList: Producto[] = [
    { id_prod: 1, nombre: 'yerba playadito 500g' , id_proovedor: 2, precio: 43, stock: 150 },
    { id_prod: 2, nombre: 'pan x kg ' , id_proovedor: 3, precio: 20, stock: 7 },
    { id_prod: 3, nombre: 'agua villa del sur 1.5L' , id_proovedor: 2, precio: 35, stock: 10 },
    { id_prod: 4, nombre: 'cigarrillos phillip 10' , id_proovedor: 1, precio: 40, stock: 80 },
    { id_prod: 5, nombre: 'yerba amanda 1kg' , id_proovedor: 5, precio: 90, stock: 60 },
    { id_prod: 6, nombre: 'jugo tang manzana' , id_proovedor: 4, precio: 10, stock: 40 },
    { id_prod: 7, nombre: 'chicles beldent menta' , id_proovedor: 4, precio: 3.5, stock: 70 },
    { id_prod: 8, nombre: 'cigarrillos marlboro 20 box' , id_proovedor: 3, precio: 68, stock: 8 },
    { id_prod: 9, nombre: 'papas lays 125g' , id_proovedor: 2, precio: 33, stock: 34 },
    { id_prod: 10, nombre: 'yerba playadito 1kg' , id_proovedor: 2, precio: 43, stock: 150 },
    { id_prod: 11, nombre: 'chicles topline fruta ' , id_proovedor: 3, precio: 20, stock: 7 },
    { id_prod: 12, nombre: 'agua sierra de los padres 1.5L' , id_proovedor: 2, precio: 35, stock: 10 },
    { id_prod: 13, nombre: 'cigarrillos phillip 20 box' , id_proovedor: 1, precio: 40, stock: 80 },
    { id_prod: 14, nombre: 'cafe nescafe 500g' , id_proovedor: 5, precio: 90, stock: 60 },
    { id_prod: 15, nombre: 'jugo tang pera' , id_proovedor: 4, precio: 10, stock: 40 },
    { id_prod: 16, nombre: 'azucar ledesma 1kg' , id_proovedor: 4, precio: 3.5, stock: 70 },
    { id_prod: 17, nombre: 'galletas cachafaz integral choco y mani' , id_proovedor: 3, precio: 68, stock: 8 },
    { id_prod: 18, nombre: 'don satur agridulces' , id_proovedor: 3, precio: 68, stock: 8 },
    { id_prod: 19, nombre: 'don satur saladas' , id_proovedor: 2, precio: 33, stock: 34 },
    { id_prod: 20, nombre: 'yerba amanda 500g' , id_proovedor: 2, precio: 43, stock: 150 },
    { id_prod: 21, nombre: 'shampoo plusbelle manzana 1L' , id_proovedor: 3, precio: 20, stock: 7 },
    { id_prod: 22, nombre: 'cafe dolca plus 500g' , id_proovedor: 2, precio: 35, stock: 10 },
    { id_prod: 23, nombre: 'cigarrillos redpoint 20' , id_proovedor: 1, precio: 40, stock: 80 },
    { id_prod: 24, nombre: 'galletas de arroz pepito' , id_proovedor: 5, precio: 90, stock: 60 },
    { id_prod: 25, nombre: 'jugo tang limon' , id_proovedor: 4, precio: 10, stock: 40 },
    { id_prod: 26, nombre: 'chicles beldent sabor caca' , id_proovedor: 4, precio: 3.5, stock: 70 },
    { id_prod: 27, nombre: 'cigarrillos lucky strike 20' , id_proovedor: 3, precio: 68, stock: 8 },
    { id_prod: 28, nombre: 'cigarrillos lucky strike 10' , id_proovedor: 3, precio: 35, stock: 10 },
    { id_prod: 29, nombre: 'papas lays 250g' , id_proovedor: 2, precio: 33, stock: 34 },
    { id_prod: 30, nombre: 'yerba la tranquera 500g' , id_proovedor: 2, precio: 43, stock: 150 },
    { id_prod: 31, nombre: 'pan x kg' , id_proovedor: 3, precio: 20, stock: 7 },
    { id_prod: 32, nombre: 'jamon x 100g' , id_proovedor: 2, precio: 35, stock: 10 },
    { id_prod: 33, nombre: 'queso x 100g' , id_proovedor: 1, precio: 40, stock: 80 },
    { id_prod: 34, nombre: 'toall always con alas x 8' , id_proovedor: 5, precio: 90, stock: 60 },
    { id_prod: 35, nombre: 'toall siemprelibre x 8' , id_proovedor: 4, precio: 10, stock: 40 },
    { id_prod: 36, nombre: 'esponja mortimer' , id_proovedor: 4, precio: 3.5, stock: 70 },
    { id_prod: 37, nombre: 'villa del sur levite manzana 1.5L' , id_proovedor: 3, precio: 80, stock: 8 },
    { id_prod: 38, nombre: 'villa del sur levite pomelo 1.5L' , id_proovedor: 3, precio: 68, stock: 8 },
    { id_prod: 39, nombre: 'papas krachitos 500g' , id_proovedor: 2, precio: 33, stock: 34 },
    { id_prod: 40, nombre: 'gatorade manzana 500ml' , id_proovedor: 2, precio: 43, stock: 150 },


];
